//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookInspiredApp.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentResource
    {
        public int Appointments_AppointmentID { get; set; }
        public int Resources_ResourceID { get; set; }
        public Nullable<bool> ManyToManyWorkaround { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
