//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookInspiredApp.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.AppointmentResources = new HashSet<AppointmentResource>();
            this.ExceptionOccurrences = new HashSet<ExceptionOccurrence>();
        }
    
        public int AppointmentID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public bool IsAllDayEvent { get; set; }
        public string RecurrencePattern { get; set; }
        public string TimeZoneString { get; set; }
        public int Importance { get; set; }
        public Nullable<int> TimeMarkerID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ICollection<AppointmentResource> AppointmentResources { get; set; }
        public virtual Category Category { get; set; }
        public virtual TimeMarker TimeMarker { get; set; }
        public virtual ICollection<ExceptionOccurrence> ExceptionOccurrences { get; set; }
    }
}
