//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookInspiredApp.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Emails = new HashSet<Email>();
            this.ExceptionAppointments = new HashSet<ExceptionAppointment>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string DisplayName { get; set; }
        public string CategoryBrush { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<ExceptionAppointment> ExceptionAppointments { get; set; }
    }
}
