//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookInspiredApp.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailClient
    {
        public EmailClient()
        {
            this.Emails = new HashSet<Email>();
            this.Folders = new HashSet<Folder>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<Folder> Folders { get; set; }
    }
}
