//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookInspiredApp.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionOccurrence
    {
        public int ExceptionID { get; set; }
        public int MasterAppointmentID { get; set; }
        public System.DateTime ExceptionDate { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual ExceptionAppointment ExceptionAppointment { get; set; }
    }
}
