//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookInspiredApp.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionResource
    {
        public int ExceptionAppointmentID { get; set; }
        public int ExceptionAppointmentResourcesID { get; set; }
        public Nullable<bool> ManyToManyWorkaround { get; set; }
    
        public virtual ExceptionAppointment ExceptionAppointment { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
