//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookInspiredApp.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.AppointmentResources = new HashSet<AppointmentResource>();
            this.ExceptionResources = new HashSet<ExceptionResource>();
        }
    
        public int ResourceID { get; set; }
        public int ResourceTypeID { get; set; }
        public string ResourceName { get; set; }
        public string DisplayName { get; set; }
        public string ResourceBrush { get; set; }
    
        public virtual ICollection<AppointmentResource> AppointmentResources { get; set; }
        public virtual ICollection<ExceptionResource> ExceptionResources { get; set; }
        public virtual ResourceType ResourceType { get; set; }
    }
}
