//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookInspiredApp.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeMarker
    {
        public TimeMarker()
        {
            this.Appointments = new HashSet<Appointment>();
            this.ExceptionAppointments = new HashSet<ExceptionAppointment>();
        }
    
        public int TimeMarkerID { get; set; }
        public string TimeMarkerName { get; set; }
        public string TimeMarkerBrush { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<ExceptionAppointment> ExceptionAppointments { get; set; }
    }
}
